-- +goose Up
CREATE TABLE assets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id            BIGINT       NOT NULL,
    address             VARCHAR(42)  NOT NULL,
    address_checksum    VARCHAR(42)  NOT NULL,
    symbol              VARCHAR(16)  NOT NULL,
    name                VARCHAR(64)  NOT NULL,
    decimals            SMALLINT     NOT NULL,
    is_collateral       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_borrowable       BOOLEAN      NOT NULL DEFAULT FALSE,
    price_feed_address  VARCHAR(42),
    price_feed_decimals SMALLINT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT assets_address_lowercase CHECK (address = lower(address)),
    CONSTRAINT assets_decimals_range CHECK (decimals >= 0 AND decimals <= 36)
);

CREATE UNIQUE INDEX assets_chain_address_key ON assets (chain_id, address);
CREATE UNIQUE INDEX assets_chain_symbol_key ON assets (chain_id, symbol);

CREATE TABLE markets (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id                      BIGINT        NOT NULL,
    collateral_asset_id           BIGINT        NOT NULL REFERENCES assets (id) ON DELETE RESTRICT,
    debt_asset_id                 BIGINT        NOT NULL REFERENCES assets (id) ON DELETE RESTRICT,
    pool_address                  VARCHAR(42)   NOT NULL,
    collateral_vault_address      VARCHAR(42)   NOT NULL,
    controller_address            VARCHAR(42)   NOT NULL,
    liquidation_manager_address   VARCHAR(42)   NOT NULL,
    interest_rate_model_address   VARCHAR(42)   NOT NULL,
    oracle_adapter_address        VARCHAR(42)   NOT NULL,
    max_ltv_bps                   INTEGER       NOT NULL,
    liquidation_threshold_bps     INTEGER       NOT NULL,
    liquidation_bonus_bps         INTEGER       NOT NULL,
    reserve_factor_bps            INTEGER       NOT NULL,
    recommended_ltv_bps           INTEGER       NOT NULL,
    kink_utilization_bps          INTEGER       NOT NULL,
    min_deposit                   NUMERIC(78,0) NOT NULL,
    status                        VARCHAR(16)   NOT NULL DEFAULT 'active',
    deployed_at_block             BIGINT        NOT NULL,
    created_at                    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT markets_status_allowed CHECK (status IN ('active', 'deposit_only', 'deprecated')),
    CONSTRAINT markets_ltv_below_threshold CHECK (max_ltv_bps < liquidation_threshold_bps),
    CONSTRAINT markets_recommended_below_ltv CHECK (recommended_ltv_bps <= max_ltv_bps),
    CONSTRAINT markets_bps_ranges CHECK (
        max_ltv_bps > 0 AND max_ltv_bps <= 10000
        AND liquidation_threshold_bps > 0 AND liquidation_threshold_bps <= 10000
        AND liquidation_bonus_bps >= 0 AND liquidation_bonus_bps <= 10000
        AND reserve_factor_bps >= 0 AND reserve_factor_bps <= 10000
        AND recommended_ltv_bps > 0
        AND kink_utilization_bps > 0 AND kink_utilization_bps <= 10000
    ),
    CONSTRAINT markets_min_deposit_positive CHECK (min_deposit >= 0),
    CONSTRAINT markets_assets_differ CHECK (collateral_asset_id <> debt_asset_id)
);

CREATE UNIQUE INDEX markets_chain_pool_key ON markets (chain_id, pool_address);
CREATE INDEX markets_status_idx ON markets (status);

CREATE TABLE market_parameter_history (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id         BIGINT        NOT NULL REFERENCES markets (id) ON DELETE CASCADE,
    parameter_name    VARCHAR(48)   NOT NULL,
    old_value         NUMERIC(78,0),
    new_value         NUMERIC(78,0) NOT NULL,
    changed_at_block  BIGINT        NOT NULL,
    block_time        TIMESTAMPTZ   NOT NULL,
    tx_hash           VARCHAR(66),
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX market_parameter_history_market_block_idx
    ON market_parameter_history (market_id, changed_at_block DESC);

-- +goose Down
DROP TABLE IF EXISTS market_parameter_history;
DROP TABLE IF EXISTS markets;
DROP TABLE IF EXISTS assets;
