-- +goose Up
CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    kind       VARCHAR(32)  NOT NULL,
    severity   VARCHAR(16)  NOT NULL,
    title      VARCHAR(160) NOT NULL,
    body       TEXT         NOT NULL,
    payload    JSONB,
    dedupe_key VARCHAR(120),
    read_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT notifications_kind_allowed CHECK (kind IN (
        'health_warning', 'liquidation', 'rate_change', 'announcement'
    )),
    CONSTRAINT notifications_severity_allowed CHECK (severity IN ('info', 'caution', 'critical'))
);

CREATE INDEX notifications_user_created_idx ON notifications (user_id, created_at DESC);
CREATE INDEX notifications_user_unread_idx ON notifications (user_id) WHERE read_at IS NULL;
CREATE UNIQUE INDEX notifications_user_dedupe_key
    ON notifications (user_id, dedupe_key) WHERE dedupe_key IS NOT NULL;

CREATE TABLE email_messages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    notification_id     BIGINT       REFERENCES notifications (id) ON DELETE SET NULL,
    to_email            VARCHAR(320) NOT NULL,
    template            VARCHAR(64)  NOT NULL,
    payload             JSONB        NOT NULL,
    status              VARCHAR(16)  NOT NULL DEFAULT 'pending',
    attempts            SMALLINT     NOT NULL DEFAULT 0,
    last_error          TEXT,
    provider_message_id VARCHAR(128),
    scheduled_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    sent_at             TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT email_messages_status_allowed CHECK (status IN (
        'pending', 'sending', 'sent', 'failed', 'cancelled'
    )),
    CONSTRAINT email_messages_attempts_non_negative CHECK (attempts >= 0)
);

CREATE INDEX email_messages_dispatch_idx
    ON email_messages (status, scheduled_at) WHERE status IN ('pending', 'failed');
CREATE INDEX email_messages_user_created_idx ON email_messages (user_id, created_at DESC);

-- +goose Down
DROP TABLE IF EXISTS email_messages;
DROP TABLE IF EXISTS notifications;
