-- +goose Up
CREATE TABLE faucet_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    asset_id     BIGINT        NOT NULL REFERENCES assets (id) ON DELETE RESTRICT,
    amount       NUMERIC(78,0) NOT NULL,
    status       VARCHAR(16)   NOT NULL DEFAULT 'pending',
    tx_hash      VARCHAR(66),
    request_ip   INET,
    error        TEXT,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT faucet_requests_status_allowed CHECK (status IN (
        'pending', 'sending', 'completed', 'failed'
    )),
    CONSTRAINT faucet_requests_amount_positive CHECK (amount > 0)
);

CREATE INDEX faucet_requests_user_asset_created_idx
    ON faucet_requests (user_id, asset_id, created_at DESC);
CREATE INDEX faucet_requests_ip_created_idx
    ON faucet_requests (request_ip, created_at DESC) WHERE request_ip IS NOT NULL;
CREATE INDEX faucet_requests_pending_idx
    ON faucet_requests (created_at) WHERE status IN ('pending', 'sending');

CREATE TABLE idempotency_keys (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key             VARCHAR(80) NOT NULL,
    scope           VARCHAR(64) NOT NULL,
    request_hash    CHAR(64)    NOT NULL,
    response_status SMALLINT,
    response_body   JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX idempotency_keys_scope_key ON idempotency_keys (scope, key);
CREATE INDEX idempotency_keys_expires_idx ON idempotency_keys (expires_at);

CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor       VARCHAR(128) NOT NULL,
    action      VARCHAR(64)  NOT NULL,
    entity_type VARCHAR(48)  NOT NULL,
    entity_id   BIGINT,
    before      JSONB,
    after       JSONB,
    request_ip  INET,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX audit_logs_entity_idx ON audit_logs (entity_type, entity_id, created_at DESC);
CREATE INDEX audit_logs_created_idx ON audit_logs (created_at DESC);

-- +goose Down
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS idempotency_keys;
DROP TABLE IF EXISTS faucet_requests;
