-- +goose Up
CREATE TABLE indexer_checkpoints (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_name               VARCHAR(64) NOT NULL,
    chain_id                  BIGINT      NOT NULL,
    last_processed_block      BIGINT      NOT NULL DEFAULT 0,
    last_processed_log_index  INTEGER     NOT NULL DEFAULT -1,
    last_processed_block_hash VARCHAR(66),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT indexer_checkpoints_block_non_negative CHECK (last_processed_block >= 0)
);

CREATE UNIQUE INDEX indexer_checkpoints_stream_key ON indexer_checkpoints (stream_name);

CREATE TABLE indexed_blocks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id     BIGINT      NOT NULL,
    block_number BIGINT      NOT NULL,
    block_hash   VARCHAR(66) NOT NULL,
    parent_hash  VARCHAR(66) NOT NULL,
    block_time   TIMESTAMPTZ NOT NULL,
    is_finalized BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX indexed_blocks_chain_number_key ON indexed_blocks (chain_id, block_number);
CREATE INDEX indexed_blocks_chain_hash_idx ON indexed_blocks (chain_id, block_hash);

CREATE TABLE reorg_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id      BIGINT      NOT NULL,
    detected_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    from_block    BIGINT      NOT NULL,
    to_block      BIGINT      NOT NULL,
    rows_reverted INTEGER     NOT NULL DEFAULT 0,
    notes         TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT reorg_events_block_range CHECK (to_block >= from_block)
);

CREATE INDEX reorg_events_detected_idx ON reorg_events (detected_at DESC);

-- +goose Down
DROP TABLE IF EXISTS reorg_events;
DROP TABLE IF EXISTS indexed_blocks;
DROP TABLE IF EXISTS indexer_checkpoints;
