-- +goose Up
CREATE TABLE market_snapshots (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id           BIGINT        NOT NULL REFERENCES markets (id) ON DELETE CASCADE,
    captured_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    block_number        BIGINT        NOT NULL,
    total_supplied      NUMERIC(78,0) NOT NULL,
    total_borrowed      NUMERIC(78,0) NOT NULL,
    available_liquidity NUMERIC(78,0) NOT NULL,
    utilization_bps     INTEGER       NOT NULL,
    supply_rate_bps     INTEGER       NOT NULL,
    borrow_rate_bps     INTEGER       NOT NULL,
    supply_index        NUMERIC(78,0) NOT NULL,
    borrow_index        NUMERIC(78,0) NOT NULL,
    positions_at_risk   INTEGER       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT market_snapshots_amounts_non_negative CHECK (
        total_supplied >= 0 AND total_borrowed >= 0 AND available_liquidity >= 0
    ),
    CONSTRAINT market_snapshots_bps_non_negative CHECK (
        utilization_bps >= 0 AND supply_rate_bps >= 0 AND borrow_rate_bps >= 0
    ),
    CONSTRAINT market_snapshots_positions_non_negative CHECK (positions_at_risk >= 0)
);

CREATE UNIQUE INDEX market_snapshots_market_block_key ON market_snapshots (market_id, block_number);
CREATE INDEX market_snapshots_market_captured_idx ON market_snapshots (market_id, captured_at DESC);

CREATE TABLE price_observations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id       BIGINT        NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
    price          NUMERIC(78,0) NOT NULL,
    price_decimals SMALLINT      NOT NULL,
    source         VARCHAR(24)   NOT NULL,
    round_id       NUMERIC(78,0),
    observed_at    TIMESTAMPTZ   NOT NULL,
    fetched_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    is_stale       BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT price_observations_source_allowed CHECK (source IN ('chainlink', 'fallback', 'manual')),
    CONSTRAINT price_observations_price_positive CHECK (price > 0),
    CONSTRAINT price_observations_decimals_range CHECK (price_decimals >= 0 AND price_decimals <= 36)
);

CREATE UNIQUE INDEX price_observations_asset_source_round_key
    ON price_observations (asset_id, source, round_id) WHERE round_id IS NOT NULL;
CREATE INDEX price_observations_asset_observed_idx ON price_observations (asset_id, observed_at DESC);

-- +goose Down
DROP TABLE IF EXISTS price_observations;
DROP TABLE IF EXISTS market_snapshots;
