-- +goose Up
CREATE TABLE protocol_events (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id         BIGINT      NOT NULL,
    market_id        BIGINT      REFERENCES markets (id) ON DELETE RESTRICT,
    event_type       VARCHAR(32) NOT NULL,
    contract_address VARCHAR(42) NOT NULL,
    block_number     BIGINT      NOT NULL,
    block_hash       VARCHAR(66) NOT NULL,
    block_time       TIMESTAMPTZ NOT NULL,
    tx_hash          VARCHAR(66) NOT NULL,
    tx_index         INTEGER     NOT NULL,
    log_index        INTEGER     NOT NULL,
    actor_user_id    BIGINT      REFERENCES users (id) ON DELETE RESTRICT,
    payload          JSONB       NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT protocol_events_type_allowed CHECK (event_type IN (
        'deposit', 'withdraw', 'borrow', 'repay',
        'collateral_added', 'collateral_withdrawn',
        'liquidation', 'interest_accrued', 'parameter_changed'
    )),
    CONSTRAINT protocol_events_log_index_non_negative CHECK (log_index >= 0)
);

CREATE UNIQUE INDEX protocol_events_chain_tx_log_key
    ON protocol_events (chain_id, tx_hash, log_index);
CREATE INDEX protocol_events_block_idx ON protocol_events (block_number DESC);
CREATE INDEX protocol_events_market_type_time_idx
    ON protocol_events (market_id, event_type, block_time DESC);
CREATE INDEX protocol_events_actor_time_idx
    ON protocol_events (actor_user_id, block_time DESC) WHERE actor_user_id IS NOT NULL;

CREATE TABLE user_transactions (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id                BIGINT        NOT NULL REFERENCES protocol_events (id) ON DELETE CASCADE,
    user_id                 BIGINT        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    market_id               BIGINT        NOT NULL REFERENCES markets (id) ON DELETE RESTRICT,
    asset_id                BIGINT        NOT NULL REFERENCES assets (id) ON DELETE RESTRICT,
    kind                    VARCHAR(24)   NOT NULL,
    amount                  NUMERIC(78,0) NOT NULL,
    health_factor_after_bps INTEGER,
    block_number            BIGINT        NOT NULL,
    block_time              TIMESTAMPTZ   NOT NULL,
    tx_hash                 VARCHAR(66)   NOT NULL,
    log_index               INTEGER       NOT NULL,
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT user_transactions_kind_allowed CHECK (kind IN (
        'deposit', 'withdraw', 'borrow', 'repay',
        'collateral_added', 'collateral_withdrawn', 'liquidation'
    )),
    CONSTRAINT user_transactions_amount_positive CHECK (amount > 0),
    CONSTRAINT user_transactions_health_non_negative
        CHECK (health_factor_after_bps IS NULL OR health_factor_after_bps >= 0)
);

CREATE UNIQUE INDEX user_transactions_event_key ON user_transactions (event_id);
CREATE INDEX user_transactions_user_time_idx
    ON user_transactions (user_id, block_time DESC, id DESC);
CREATE INDEX user_transactions_user_kind_time_idx
    ON user_transactions (user_id, kind, block_time DESC);
CREATE INDEX user_transactions_tx_hash_idx ON user_transactions (tx_hash);

CREATE TABLE positions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    market_id          BIGINT        NOT NULL REFERENCES markets (id) ON DELETE RESTRICT,
    supply_shares      NUMERIC(78,0) NOT NULL DEFAULT 0,
    collateral_amount  NUMERIC(78,0) NOT NULL DEFAULT 0,
    debt_scaled        NUMERIC(78,0) NOT NULL DEFAULT 0,
    last_supply_index  NUMERIC(78,0),
    last_borrow_index  NUMERIC(78,0),
    health_factor_bps  INTEGER,
    collateral_value   NUMERIC(78,0),
    debt_value         NUMERIC(78,0),
    is_liquidatable    BOOLEAN       NOT NULL DEFAULT FALSE,
    liquidatable_since TIMESTAMPTZ,
    valued_at_price    NUMERIC(78,0),
    valued_at_block    BIGINT,
    valued_at          TIMESTAMPTZ,
    last_event_block   BIGINT        NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT positions_amounts_non_negative CHECK (
        supply_shares >= 0 AND collateral_amount >= 0 AND debt_scaled >= 0
    )
);

CREATE UNIQUE INDEX positions_user_market_key ON positions (user_id, market_id);
CREATE INDEX positions_liquidatable_idx
    ON positions (market_id, health_factor_bps ASC) WHERE is_liquidatable = TRUE;
CREATE INDEX positions_with_debt_idx
    ON positions (market_id, health_factor_bps ASC) WHERE debt_scaled > 0;
CREATE INDEX positions_valued_at_idx ON positions (valued_at);

CREATE TABLE liquidations (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id                  BIGINT        NOT NULL REFERENCES protocol_events (id) ON DELETE CASCADE,
    market_id                 BIGINT        NOT NULL REFERENCES markets (id) ON DELETE RESTRICT,
    borrower_user_id          BIGINT        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    liquidator_user_id        BIGINT        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    debt_repaid               NUMERIC(78,0) NOT NULL,
    collateral_seized         NUMERIC(78,0) NOT NULL,
    bonus_amount              NUMERIC(78,0) NOT NULL,
    health_factor_before_bps  INTEGER,
    trigger_price             NUMERIC(78,0) NOT NULL,
    trigger_price_decimals    SMALLINT      NOT NULL,
    shortfall_amount          NUMERIC(78,0) NOT NULL DEFAULT 0,
    block_number              BIGINT        NOT NULL,
    block_time                TIMESTAMPTZ   NOT NULL,
    tx_hash                   VARCHAR(66)   NOT NULL,
    created_at                TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT liquidations_amounts_non_negative CHECK (
        debt_repaid > 0 AND collateral_seized >= 0
        AND bonus_amount >= 0 AND shortfall_amount >= 0
    ),
    CONSTRAINT liquidations_parties_differ CHECK (borrower_user_id <> liquidator_user_id)
);

CREATE UNIQUE INDEX liquidations_event_key ON liquidations (event_id);
CREATE INDEX liquidations_market_time_idx ON liquidations (market_id, block_time DESC);
CREATE INDEX liquidations_borrower_time_idx ON liquidations (borrower_user_id, block_time DESC);
CREATE INDEX liquidations_liquidator_time_idx ON liquidations (liquidator_user_id, block_time DESC);
CREATE INDEX liquidations_shortfall_idx ON liquidations (block_time DESC) WHERE shortfall_amount > 0;

-- +goose Down
DROP TABLE IF EXISTS liquidations;
DROP TABLE IF EXISTS positions;
DROP TABLE IF EXISTS user_transactions;
DROP TABLE IF EXISTS protocol_events;
