-- +goose Up
CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address           VARCHAR(42)  NOT NULL,
    address_checksum  VARCHAR(42)  NOT NULL,
    nickname          VARCHAR(64),
    email             VARCHAR(320),
    email_verified_at TIMESTAMPTZ,
    first_seen_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_seen_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT users_address_lowercase CHECK (address = lower(address)),
    CONSTRAINT users_address_format CHECK (address ~ '^0x[0-9a-f]{40}$')
);

CREATE UNIQUE INDEX users_address_key ON users (address);
CREATE INDEX users_email_idx ON users (email) WHERE email IS NOT NULL;

CREATE TABLE user_notification_preferences (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    health_alert_threshold_bps INTEGER     NOT NULL DEFAULT 12000,
    in_app_enabled             BOOLEAN     NOT NULL DEFAULT TRUE,
    email_enabled              BOOLEAN     NOT NULL DEFAULT FALSE,
    rate_change_enabled        BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT user_notification_preferences_threshold_range
        CHECK (health_alert_threshold_bps > 10000 AND health_alert_threshold_bps <= 50000)
);

CREATE UNIQUE INDEX user_notification_preferences_user_key
    ON user_notification_preferences (user_id);

CREATE TABLE email_verification_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    email       VARCHAR(320) NOT NULL,
    token_hash  CHAR(64)     NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX email_verification_tokens_hash_key ON email_verification_tokens (token_hash);
CREATE INDEX email_verification_tokens_user_expiry_idx
    ON email_verification_tokens (user_id, expires_at DESC);

-- +goose Down
DROP TABLE IF EXISTS email_verification_tokens;
DROP TABLE IF EXISTS user_notification_preferences;
DROP TABLE IF EXISTS users;
